// This file was autogenerated by closure/library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../development/js_dev/googkit_index_step2.js', ['googkit_index_step2'], ['goog.Uri', 'goog.debug', 'goog.dom', 'goog.dom.forms', 'goog.events', 'goog.events.EventType', 'goog.net.EventType', 'goog.net.XhrIo']);
