/**
 * @fileoverview An entry point of the web app. This script was automatically
 * generated by googkit.
 */

goog.provide('googkit_index_step2');/*@provide_main@*/

goog.require('goog.Uri');
goog.require('goog.debug');
goog.require('goog.dom');
goog.require('goog.dom.forms');
goog.require('goog.events');
goog.require('goog.events.EventType');
goog.require('goog.net.EventType');
goog.require('goog.net.XhrIo');

var sel = goog.dom.getElement('bloodTypeBox');
var resArea = goog.dom.getElement('resultArea');

var handleListChange = function(e) {
  var bloodType = goog.dom.forms.getValue(sel);
  if (bloodType === 'default') {
    return;
  }
  var url = './result/type-' + bloodType + '.txt';
  var xhrio = new goog.net.XhrIo();
  goog.events.listen(xhrio, goog.net.EventType.SUCCESS, handleXhrIoSuccess);
  goog.events.listen(xhrio, goog.net.EventType.ERROR, handleXhrIoError);
  xhrio.send(url);
};

var handleXhrIoSuccess = function(e) {
  var xhrio = e.target;
  var res = xhrio.getResponseText();
  goog.dom.setTextContent(resArea, res);
};

var handleXhrIoError = function(e) {
  console.log(e);
};

goog.events.listen(sel, goog.events.EventType.CHANGE, handleListChange);
